import type { PublicCategory, PublicProductCard } from "@/types/storefront";

export const FALLBACK_CATEGORIES: PublicCategory[] = [
  {
    id: "fallback-protein",
    name: "Protein",
    slug: "protein",
    isFeature: true,
    image: null,
  },
  {
    id: "fallback-preworkout",
    name: "Pre-Workout",
    slug: "pre-workout",
    isFeature: true,
    image: null,
  },
  {
    id: "fallback-creatine",
    name: "Creatine",
    slug: "creatine",
    isFeature: true,
    image: null,
  },
  {
    id: "fallback-vitamins",
    name: "Vitamins",
    slug: "vitamins",
    isFeature: false,
    image: null,
  },
];

export const FALLBACK_PRODUCTS: PublicProductCard[] = [
  {
    id: "fallback-1",
    slug: "forge-whey-isolate",
    title: "Forge Whey Isolate",
    summary: "Ultra-clean 25g protein per scoop with fast absorption.",
    basePrice: "49.99",
    rating: "4.8",
    thumbnailUrl: null,
    minPrice: "49.99",
    maxPrice: "59.99",
    brand: { id: "b1", name: "Crimson Forge", slug: "crimson-forge" },
    category: { id: "c1", name: "Protein", slug: "protein" },
  },
  {
    id: "fallback-2",
    slug: "ignite-pre-workout",
    title: "Ignite Pre-Workout",
    summary: "Clean energy, focus, and pump without the crash.",
    basePrice: "39.99",
    rating: "4.7",
    thumbnailUrl: null,
    minPrice: "39.99",
    maxPrice: "39.99",
    brand: { id: "b1", name: "Crimson Forge", slug: "crimson-forge" },
    category: { id: "c2", name: "Pre-Workout", slug: "pre-workout" },
  },
  {
    id: "fallback-3",
    slug: "pure-creatine-mono",
    title: "Pure Creatine Monohydrate",
    summary: "Micronized creatine for strength and recovery support.",
    basePrice: "24.99",
    rating: "4.9",
    thumbnailUrl: null,
    minPrice: "24.99",
    maxPrice: "29.99",
    brand: { id: "b2", name: "Iron Labs", slug: "iron-labs" },
    category: { id: "c3", name: "Creatine", slug: "creatine" },
  },
  {
    id: "fallback-4",
    slug: "daily-performance-stack",
    title: "Daily Performance Stack",
    summary: "Essential vitamins and minerals for active lifestyles.",
    basePrice: "34.99",
    rating: "4.6",
    thumbnailUrl: null,
    minPrice: "34.99",
    maxPrice: "34.99",
    brand: { id: "b3", name: "Peak Nutrition", slug: "peak-nutrition" },
    category: { id: "c4", name: "Vitamins", slug: "vitamins" },
  },
];
